module.exports = {
  LOAD_STATIONS: 'LOAD_STATIONS',
  SET_ACTIVE_STATION: 'SET_ACTIVE_STATION',
  SET_SOURCE: 'SET_SOURCE',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  PLAY_PAUSE: 'PLAY_PAUSE',
  KEY_PRESS: 'KEY_PRESS'
}
